name: Build and test RTCV
on: [push, pull_request]

jobs:
  buildAndTest:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.0
    - name: Restore packages
      run: msbuild RTCV.sln /t:restore
    - name: Build with MSBuild
      run: msbuild RTCV.sln
    - name: Run tests with MSTest # Thanks to this post https://stackoverflow.com/a/62010912/1222411
      run: '& "$(vswhere -property installationPath)\Common7\IDE\MSTest.exe" /testcontainer:Build\SerializationTests.dll'
