name: Build
on: [push, pull_request]

jobs:
  RTCV:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - name: Restore packages
      run: msbuild RTCV.sln /t:restore
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.0
    - name: Build with MSBuild
      run: msbuild RTCV.sln
