name: Build all dependants
on:
  push:
    branches:
      - '505' # Bizhawk and CemuStub depend on RTCV 505
      - 'GithubActionTest'
  pull_request:
    branches:
      - '505' # Bizhawk and CemuStub depend on RTCV 505

jobs:
  Bizhawk:
    runs-on: windows-2019
    steps:
    # Checkout relevant code
    - name: Checkout current build target
      uses: actions/checkout@v2
      with:
        path: 'RTCV'
    - name: Checkout Bizhawk
      uses: actions/checkout@v2
      with:
        repository: 'ircluzar/Bizhawk-Vanguard'
        ref: 'master'
        path: 'Bizhawk-Vanguard'

    # Setup Tooling
    - name: Setup Nuget
      uses: nuget/setup-nuget@v1.0.2
      with:
        nuget-version: 'latest'
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.0

    # Restore nuget packages for all targets
    - name: Restore Nuget packages in current build target
      run: nuget restore '.\RTCV\'
    - name: Restore Nuget packages in Bizhawk
      run: nuget restore '.\Bizhawk-Vanguard\Real-Time Corruptor\BizHawk_RTC\BizHawk.sln'

    # Build Bizhawk
    - name: Build Bizhawk-Vanguard
      run: msbuild '.\Bizhawk-Vanguard\Real-Time Corruptor\BizHawk_RTC\BizHawk.sln'

  CemuStub:
    runs-on: windows-2019
    steps:
    # Checkout relevant code
    - name: Checkout current build target
      uses: actions/checkout@v2
      with:
        path: 'RTCV'
    - name: Checkout CemuStub
      uses: actions/checkout@v2
      with:
        repository: 'ircluzar/CemuStub-Vanguard'
        ref: 'master'
        path: 'CemuStub-Vanguard'

    # Setup Tooling
    - name: Setup Nuget
      uses: nuget/setup-nuget@v1.0.2
      with:
        nuget-version: 'latest'
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.0

    # Restore nuget packages for all targets
    - name: Restore Nuget packages in current build target
      run: nuget restore '.\RTCV\'
    - name: Restore Nuget packages in CemuStub
      run: nuget restore '.\CemuStub-Vanguard\'

    # Build CemuStub
    - name: Build CemuStub-Vanguard
      run: msbuild '.\CemuStub-Vanguard\'

  FileStub:
    runs-on: windows-2019
    steps:
    # Checkout relevant code
    - name: Checkout current build target
      uses: actions/checkout@v2
      with:
        path: 'RTCV'
    - name: Checkout FileStub
      uses: actions/checkout@v2
      with:
        repository: 'ircluzar/FileStub-Vanguard'
        ref: 'master'
        path: 'FileStub-Vanguard'

    # Setup Tooling
    - name: Setup Nuget
      uses: nuget/setup-nuget@v1.0.2
      with:
        nuget-version: 'latest'
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.0

    # Restore nuget packages for all targets
    - name: Restore Nuget packages in current build target
      run: nuget restore '.\RTCV\'
    - name: Restore Nuget packages in FileStub
      run: nuget restore '.\FileStub-Vanguard\FileStub-Vanguard.sln'

    # Build FileStub
    - name: Build FileStub-Vanguard
      run: msbuild '.\FileStub-Vanguard\FileStub-Vanguard.sln'

  UnityStub:
    runs-on: windows-2019
    steps:
    # Checkout relevant code
    - name: Checkout current build target
      uses: actions/checkout@v2
      with:
        path: 'RTCV'
    - name: Checkout UnityStub
      uses: actions/checkout@v2
      with:
        repository: 'ircluzar/UnityStub-Vanguard'
        ref: 'master'
        path: 'UnityStub-Vanguard'

    # Setup Tooling
    - name: Setup Nuget
      uses: nuget/setup-nuget@v1.0.2
      with:
        nuget-version: 'latest'
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.0

    # Restore nuget packages for all targets
    - name: Restore Nuget packages in current build target
      run: nuget restore '.\RTCV\'
    - name: Restore Nuget packages in UnityStub
      run: nuget restore '.\UnityStub-Vanguard\UnityStub-Vanguard.sln'

    # Build UnityStub
    - name: Build UnityStub-Vanguard
      run: msbuild '.\UnityStub-Vanguard\UnityStub-Vanguard.sln'

  ProcessStub:
    runs-on: windows-2019
    steps:
    # Checkout relevant code
    - name: Checkout current build target
      uses: actions/checkout@v2
      with:
        path: 'RTCV'
    - name: Checkout ProcessStub
      uses: actions/checkout@v2
      with:
        repository: 'NarryG/ProcessStub-Vanguard'
        ref: 'master'
        path: 'ProcessStub-Vanguard'

    # Setup Tooling
    - name: Setup Nuget
      uses: nuget/setup-nuget@v1.0.2
      with:
        nuget-version: 'latest'
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.0

    # Restore nuget packages for all targets
    - name: Restore Nuget packages in current build target
      run: nuget restore '.\RTCV\'
    - name: Restore Nuget packages in ProcessStub
      run: nuget restore '.\ProcessStub-Vanguard\ProcessStub-Vanguard.sln'

    # Build ProcessStub
    - name: Build ProcessStub-Vanguard
      run: msbuild '.\ProcessStub-Vanguard\ProcessStub-Vanguard.sln'