name: Build
on: push

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Setup .NET 4.7.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '4.7.1'
      - name: Build with .NET
        run: dotnet build RTCV.sln